FROM php:5.6-fpm-alpine


RUN docker-php-ext-install mysql
RUN docker-php-ext-install mysqli

RUN sed -i '/phpize/i \
	[[ ! -f "config.m4" && -f "config0.m4" ]] && mv config0.m4 config.m4' \
	/usr/local/bin/docker-php-ext-configure

RUN mkdir /code && chown -R www-data:www-data /code
